### ISSUE TITLE
Option to control parallelism

### ISSUE THREAD

**Issue by jml** [DRMacIver/each#9]
For some processes, parallelism does not help. e.g. when running multiple concurrent `terraform` commands against the same state doesn't help, since Terraform maintains a lock on the state.

Rather than have the extra processes fail, only to be retried later, it would be nice to just say `-j1` (or something) and avoid the hassle altogether.

**Comment by DRMacIver** [comment]
There is one! `--processes=1` does what you want. Having a `-j` short form might be nice though.

**Comment by jml** [comment]
Cool. Maybe a documentation tweak also? "The number of child processes to run *in parallel*"?
